const SUPABASE_URL  = 'https://weptedvdrzfaulbnimmf.supabase.co';
const SUPABASE_KEY  = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndlcHRlZHZkcnpmYXVsYm5pbW1mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU5MzAyNTIsImV4cCI6MjA5MTUwNjI1Mn0.j64AZCtUBKjT2ySMlHZqbaal1rWwL7jCSX_BNqNNphI';
